str1="TGACAGGATACAGGATAGTTACAACAGGATCCAGCACAGGATTCGACAGGATTCCACAGGATTACAGGATATATAACAGGATACAGGATACAGGATGCACAGGATTACAGGATGACAGGATCGACATAGCAACAGGATTGATCACACAGGATAACAGGATACAGGATCTCACAGGATACAGGATCACAGGATACAGGATACAGGATACAGGATACAGGATAACAGGATACAGGATGACAGGATACAGGATTCCCTACAACAGGATACAGGATACAGGATCACAGGATCAGCTACAGGATCACAGGATCAACAGGATTGTTATGGCTACAGGATTTCCAGGTTGCGTGACAGGATCCACAGGATACAGGATACAGGATACAGGATAACAGGATGACAGGATTCACAGGATTCGCGAGGGCACAGGATACAGGATGAACAGGATACAGGATGACAGGATACAGGATGTCACAGAAAACAGGATTACAGGATTACAGGATACAGGATGACAGGATTACAGGATAGATACAGGATCGAACAGGATTTTCTACAGGATATTCTTGCCACAGGATTCCGGGACAGGATCTACAGGATGAAACAGGATTCCTACAGGATACAGGATGTGCAGACAGGATCTGTACAGGATGGTACCTAGACACAGGATGTTGACAGGATTACCCACAGGATAGCCAGCACAGGATAACAGGATTACAGGATTTCACAGGATACTACAGGATGACAGGATAACAGGATACTGACACAGGATAGTAAGCCGACAGGATACAGGATAACAGGATCCATTAGACAGGATGAACAGGATTTACCTAACAGGATTAAACAGGATGACATAGTCACAGGATACAGGATACAGGATGCACAGGAT"
str2="ACAGGATAC"
i=0
ans=""
while(i<=len(str1)-len(str2)):
    str3=""
    for j in range(i,i+len(str2)):
        str3+=str1[j]
    if(str2==str3):
        ans+=" "+str(i+1)
    i+=1
print(ans[1:])
